#!/bin/sh
# setup-engram-hooks.sh
# Sets up native Git hooks to automatically sync Engram memories.

set -e

# Ensure we are inside a Git repository
if [ ! -d .git ]; then
  echo "Error: .git directory not found. Please run this script from the root of your Git repository."
  exit 1
fi

HOOKS_DIR=".git/hooks"
mkdir -p "$HOOKS_DIR"

install_hook() {
  HOOK_NAME="$1"
  HOOK_PATH="$HOOKS_DIR/$HOOK_NAME"
  
  echo "Setting up hook: $HOOK_NAME..."

  # Read the hook content template
  case "$HOOK_NAME" in
    pre-commit)
      CONTENT='#!/bin/sh
# --- ENGRAM HOOK START ---
# Auto-generated by engram sync hook setup.

if command -v engram >/dev/null 2>&1; then
  echo "[Engram] Checking for new memories to sync..."
  engram sync
  
  if [ -d .engram ] || [ -f .engram/manifest.json ]; then
    git add .engram/manifest.json .engram/chunks/ 2>/dev/null || true
  fi
else
  echo "[Engram] Warning: '\''engram'\'' CLI not found. Skipping export."
fi

# Run legacy hook if it exists
if [ -x "$0.legacy" ]; then
  "$0.legacy" "$@"
fi
# --- ENGRAM HOOK END ---'
      ;;
    post-merge|post-checkout|post-rewrite)
      CONTENT='#!/bin/sh
# --- ENGRAM HOOK START ---
# Auto-generated by engram sync hook setup.

if command -v engram >/dev/null 2>&1; then
  echo "[Engram] Importing new memories..."
  engram sync --import
else
  echo "[Engram] Warning: '\''engram'\'' CLI not found. Skipping import."
fi

# Run legacy hook if it exists
if [ -x "$0.legacy" ]; then
  "$0.legacy" "$@"
fi
# --- ENGRAM HOOK END ---'
      ;;
  esac

  # If hook exists and is not already our hook, back it up
  if [ -f "$HOOK_PATH" ]; then
    if grep -q "ENGRAM HOOK START" "$HOOK_PATH"; then
      echo "  Hook already configured. Updating..."
    else
      echo "  Existing hook detected. Backing up to $HOOK_NAME.legacy..."
      mv "$HOOK_PATH" "$HOOK_PATH.legacy"
    fi
  fi

  # Write the hook
  echo "$CONTENT" > "$HOOK_PATH"
  chmod +x "$HOOK_PATH"
  echo "  Successfully installed $HOOK_NAME hook."
}

install_hook pre-commit
install_hook post-merge
install_hook post-checkout
install_hook post-rewrite

echo "Engram Git hooks configuration complete!"
